name: XMRig Benchmark

on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make XMRig executable
        run: chmod +x bin/xmrig

      - name: Run XMRig
        run: ./bin/xmrig --config=bin/config.json
